### ISSUE TITLE
mpv 疑似有内存泄漏

### ISSUE THREAD

**Issue by seanxie28** [feiyangqingyun/QWidgetDemo#32]
使用 mpvdemo 测试，手动反复打开（rtsp 和本地文件均有此问题）或关闭，在每次关闭之后都可以看到占用内存有一个明显的上升，每次上升大概几十到 100MB，并且会持续上升。

Qt 5.13.1 & MSVC2017_64bit，x64 版本。

**Comment by feiyangqingyun** [comment]
有可能，这玩意本身考虑的就是播放器，一般都是打开一个实例进行播放，完毕关闭实例。
