### ISSUE TITLE
为什么QQ交流群都加入不了呢？

### ISSUE THREAD

**Issue by Lee-Marry** [feiyangqingyun/QWidgetDemo#33]
为什么QQ交流群都加入不了呢？

**Comment by feiyangqingyun** [comment]
满员了估计

**Comment by Lee-Marry** [comment]
那咋整呢，想着在github上找到了一个靠谱的项目，看里面有没有交流群，结果还加不了；三个群，第一个群至今没同意，第二个群一直拒绝我加入，第三个群根本就搜不到。2220549465这是我的QQ，您要是方便的能否拉我进群呢。

**Comment by feiyangqingyun** [comment]
之前的群全部满员，请加群 Qt高级学习群 951393302(作者群)
