### ISSUE TITLE
framelesswidget 取消不掉上边角的圆弧

### ISSUE THREAD

**Issue by dengxinggao** [feiyangqingyun/QWidgetDemo#37]
QWidgetDemo\widget\framelesswidget 上面两个边角能不能 不做成圆弧形，看了 没有代码设置这部分

**Comment by feiyangqingyun** [comment]
样式表设置的圆弧

**Comment by dengxinggao** [comment]
仅使用了framelesscore中的内容，没有使用样式表也会是一样的效果。
除非屏蔽掉 设置背景透明。但是屏蔽背景透明是，在xp下会出现标题栏最小最大化关闭按钮

**Comment by dengxinggao** [comment]
framelesscore中没有设置样式表的
