### ISSUE TITLE
大神，您的uiDemo01，我在stackedWidget里放一个带Qlable的QWidget，结果Lable字体显示很大，是哪里设置字体了？？

### ISSUE THREAD

**Issue by xinsuinizhuan** [feiyangqingyun/QWidgetDemo#38]
![图片](https://user-images.githubusercontent.com/40679769/168479737-0957ecdc-9e9b-4033-8a08-e2477e1c9ede.png)
![图片](https://user-images.githubusercontent.com/40679769/168479747-6f5342b2-f2f8-4c95-9e33-26d0d37293fb.png)

![图片](https://user-images.githubusercontent.com/40679769/168479718-d14115c5-741b-4d4d-8ae3-8f84ea531f17.png)

**Comment by feiyangqingyun** [comment]
ui->stackedWidget->setStyleSheet("QLabel{font:60px;}");
这么大一行你没看见？
