### ISSUE TITLE
mouseline构建所二进制对应的错误

### ISSUE THREAD

**Issue by XMuli** [feiyangqingyun/QWidgetDemo#39]
如图：
![image](https://user-images.githubusercontent.com/33887845/181059159-af60726a-72e6-4df7-bb56-ad87b1f308cb.png)

qmake 看着相是没有什么问题，奇怪

![image](https://user-images.githubusercontent.com/33887845/181059703-0bd1c6a7-2ac9-4d93-9662-beb75ad03404.png)

**Comment by feiyangqingyun** [comment]
确实，已修复，将multobj2slot项目中的改成TARGET = multobj2slot
