### ISSUE TITLE
怎么看到程序合集

### ISSUE THREAD

**Issue by Ryan24G** [feiyangqingyun/QWidgetDemo#4]
您好，我这边运行的时候只能一个一个小demo的单独运行。
看您在gitee上的演示是可以有个程序，左边是菜单，可以直接选择运行任一个小demo。
是我没找到还是这个版本就没有？

**Comment by feiyangqingyun** [comment]
那个是自定义控件大全，不开源，商业版本，需要购买，不好意思！
