### ISSUE TITLE
framelessmainwindow建议考虑hidpi的情况

### ISSUE THREAD

**Issue by fjhuangcs** [feiyangqingyun/QWidgetDemo#44]
感谢大佬的代码，用了framelessmainwindow这个类，非常简洁、有效。最近在windows下测试的时候发现在高分屏下缩放窗口的功能有bug，触发缩放图标的时机错了，发现是由于代码没有考虑hidpi场景导致的。建议大佬后续能够修正这个问题。
在nativeEvent中修改一下代码应该就可以了：
            long x = GET_X_LPARAM(msg->lParam)/scale;
            long y = GET_Y_LPARAM(msg->lParam)/scale;
这个scale变量就是屏幕的缩放比例。

**Comment by feiyangqingyun** [comment]
好的，谢谢建议
